const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const PORT=Number(process.env.PORT||3000), ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DB_FILE=path.join(ROOT,'data.json'), COOKIE='order_man_session';
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.ico':'image/x-icon'};
function fresh(){return{users:[],sessions:[],orders:[]}};function load(){try{if(!fs.existsSync(DB_FILE)){const d=fresh();fs.writeFileSync(DB_FILE,JSON.stringify(d,null,2));return d}return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch(e){console.error(e);return fresh()}};let db=load();
function save(){const t=DB_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DB_FILE)};function rid(n=16){return crypto.randomBytes(n).toString('hex')};function text(v,n=120){return String(v??'').trim().replace(/\s+/g,' ').slice(0,n)};function norm(v){return text(v,50).toLowerCase()};function cls(c){return /^(I|II|III|IV|V|VI|VII|VIII)$/.test(c)};function parseCookies(req){const o={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>=0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o};
function user(u){return{id:u.id,loginId:u.loginId,firstName:u.firstName,lastName:u.lastName,username:u.username,role:u.role,createdAt:u.createdAt}};function me(req){const t=parseCookies(req)[COOKIE];const s=db.sessions.find(x=>x.token===t&&x.expiresAt>Date.now());return s?db.users.find(u=>u.id===s.userId)||null:null};function orderView(o){const s=db.users.find(u=>u.id===o.senderId),r=db.users.find(u=>u.id===o.receiverId);return{...o,senderName:s?`${s.firstName} ${s.lastName}`:'Nieznany',receiverName:r?`${r.firstName} ${r.lastName}`:'Nieznany'}};
function send(res,status,data,headers={}){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(body)};function session(res,u,remember){const token=rid(32),seconds=(remember?30:1)*86400;db.sessions=db.sessions.filter(s=>s.userId!==u.id&&s.expiresAt>Date.now());db.sessions.push({token,userId:u.id,expiresAt:Date.now()+seconds*1000});save();res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${seconds}`)};
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>100000){req.destroy();reject(new Error('Za duże żądanie'))}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(new Error('Niepoprawny JSON'))}});req.on('error',reject)})};
function auth(req,res){const u=me(req);if(!u){send(res,401,{error:'Sesja wygasła. Zaloguj się ponownie.'});return null}return u};
function cleanStudents(a){return Array.isArray(a)?a.map(s=>({name:text(s?.name,100),eats:Boolean(s?.eats)})).filter(s=>s.name):[]}
async function api(req,res,url){
 const p=url.pathname;
 try{
  if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true});
  if(req.method==='POST'&&p==='/api/register'){const b=await body(req),firstName=text(b.firstName,60),lastName=text(b.lastName,80),username=norm(b.username),password=String(b.password||''),role=text(b.role,20)||'teacher';if(!firstName||!lastName||!/^[a-z0-9._-]{3,40}$/i.test(username)||password.length<6||password.length>128||!['teacher','receiver'].includes(role))return send(res,400,{error:'Uzupełnij poprawnie wszystkie pola. Hasło: minimum 6 znaków.'});if(db.users.some(x=>x.username===username))return send(res,409,{error:'Ta nazwa użytkownika jest już zajęta.'});const salt=rid(16),hash=await new Promise((ok,no)=>crypto.scrypt(password,salt,64,(e,d)=>e?no(e):ok(d.toString('hex'))));const u={id:rid(),loginId:'OM-'+crypto.randomBytes(6).toString('hex').toUpperCase(),firstName,lastName,username,passwordHash:salt+':'+hash,role,createdAt:new Date().toISOString()};db.users.push(u);save();session(res,u,Boolean(b.rememberMe));return send(res,200,{user:user(u)})}
  if(req.method==='POST'&&p==='/api/login'){const b=await body(req),l=norm(b.login),pass=String(b.password||''),u=db.users.find(x=>x.username===l||x.loginId.toLowerCase()===l);if(!u)return send(res,401,{error:'Nieprawidłowy login/ID lub hasło.'});const [salt,want]=u.passwordHash.split(':'),got=await new Promise((ok,no)=>crypto.scrypt(pass,salt,64,(e,d)=>e?no(e):ok(d.toString('hex'))));if(got!==want)return send(res,401,{error:'Nieprawidłowy login/ID lub hasło.'});session(res,u,Boolean(b.rememberMe));return send(res,200,{user:user(u)})}
  if(req.method==='POST'&&p==='/api/logout'){const t=parseCookies(req)[COOKIE];db.sessions=db.sessions.filter(s=>s.token!==t);save();return send(res,200,{ok:true},{'Set-Cookie':`${COOKIE}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`})}
  if(req.method==='GET'&&p==='/api/me'){const u=me(req);return u?send(res,200,{user:user(u)}):send(res,401,{error:'Brak sesji.'})}
  const u=auth(req,res);if(!u)return;
  if(req.method==='GET'&&p==='/api/receivers'){const q=norm(url.searchParams.get('q')||'');return send(res,200,{users:db.users.filter(x=>x.role==='receiver'&&(!q||x.id===q||x.loginId.toLowerCase().includes(q)||x.username.includes(q)||`${x.firstName} ${x.lastName}`.toLowerCase().includes(q))).slice(0,20).map(user)})}
  if(req.method==='GET'&&p==='/api/orders/sent')return send(res,200,{orders:db.orders.filter(o=>o.senderId===u.id&&o.status==='pending').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(orderView)});
  if(req.method==='GET'&&p==='/api/orders/inbox')return send(res,200,{orders:db.orders.filter(o=>o.receiverId===u.id&&o.status==='pending').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(orderView)});
  if(req.method==='GET'&&p==='/api/orders/received')return send(res,200,{orders:db.orders.filter(o=>o.receiverId===u.id&&o.status==='received').sort((a,b)=>(b.receivedAt||'').localeCompare(a.receivedAt||'')).map(orderView)});
  if(req.method==='POST'&&p==='/api/orders'){if(u.role!=='teacher')return send(res,403,{error:'Tylko nauczyciel może wysyłać zamówienia.'});const b=await body(req),receiver=db.users.find(x=>x.id===text(b.receiverId,100)&&x.role==='receiver'),c=text(b.className,10),students=cleanStudents(b.students);if(!receiver)return send(res,400,{error:'Nie znaleziono odbieracza. Sprawdź identyfikator.'});if(!cls(c))return send(res,400,{error:'Wybierz klasę od I do VIII.'});if(!students.length)return send(res,400,{error:'Dodaj przynajmniej jednego ucznia.'});const o={id:'ORD-'+rid(6).toUpperCase(),senderId:u.id,receiverId:receiver.id,className:c,students,status:'pending',createdAt:new Date().toISOString(),receivedAt:null,updatedAt:null};db.orders.push(o);save();return send(res,201,{order:orderView(o)})}
  const match=p.match(/^\/api\/orders\/([^/]+)$/);if(match){const id=match[1];if(req.method==='PUT'){const o=db.orders.find(x=>x.id===id&&x.senderId===u.id&&x.status==='pending');if(!o)return send(res,404,{error:'Nie znaleziono aktywnego zamówienia.'});const b=await body(req),c=text(b.className,10),students=cleanStudents(b.students);if(!cls(c)||!students.length)return send(res,400,{error:'Wybierz klasę I–VIII i dodaj uczniów.'});o.className=c;o.students=students;o.updatedAt=new Date().toISOString();save();return send(res,200,{order:orderView(o)})}if(req.method==='DELETE'){const i=db.orders.findIndex(x=>x.id===id&&x.senderId===u.id&&x.status==='pending');if(i<0)return send(res,404,{error:'Nie znaleziono aktywnego zamówienia.'});db.orders.splice(i,1);save();return send(res,200,{ok:true})}}
  const ack=p.match(/^\/api\/orders\/([^/]+)\/ack$/);if(req.method==='POST'&&ack){const o=db.orders.find(x=>x.id===ack[1]&&x.receiverId===u.id&&x.status==='pending');if(!o)return send(res,404,{error:'Zamówienie nie istnieje lub zostało już odebrane.'});o.status='received';o.receivedAt=new Date().toISOString();save();return send(res,200,{ok:true,receivedAt:o.receivedAt})}
  if(req.method==='DELETE'&&p==='/api/account'){const id=u.id;db.orders=db.orders.filter(o=>o.senderId!==id&&o.receiverId!==id);db.sessions=db.sessions.filter(s=>s.userId!==id);db.users=db.users.filter(x=>x.id!==id);save();return send(res,200,{ok:true},{'Set-Cookie':`${COOKIE}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`})}
  return send(res,404,{error:'Nie znaleziono endpointu.'});
 }catch(e){
  if(e.message==='Niepoprawny JSON'||e.message==='Za duże żądanie')return send(res,400,{error:e.message});
  console.error(e);return send(res,500,{error:'Błąd serwera: '+e.message});
 }
}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'127.0.0.1'}`);if(url.pathname.startsWith('/api/'))return api(req,res,url);let f=url.pathname==='/'?'/index.html':url.pathname;f=path.normalize(f).replace(/^\.\.(\/|\\)+/,'');const file=path.join(PUBLIC,f);if(!file.startsWith(PUBLIC))return res.writeHead(403).end();fs.readFile(file,(e,d)=>{if(e)return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(d)})});
server.listen(PORT,'0.0.0.0',()=>console.log(`Order-Man działa: http://127.0.0.1:${PORT}`));
